// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdx1Qxmt89XJmQTLYuUw96E32_Yu07iPs',
    appId: '1:835318680713:web:ed6b1fbf0a8684b8a08a58',
    messagingSenderId: '835318680713',
    projectId: 'studio-4536174912-ee6ca',
    authDomain: 'studio-4536174912-ee6ca.firebaseapp.com',
    storageBucket: 'studio-4536174912-ee6ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0eUu630ezrbHNkT_gQhpiMTBGwN3aPY',
    appId: '1:835318680713:android:18a7ec9e8ccd5b48a08a58',
    messagingSenderId: '835318680713',
    projectId: 'studio-4536174912-ee6ca',
    storageBucket: 'studio-4536174912-ee6ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRGsAIHLwZrMpN0803e5n3zxQAvIt20MQ',
    appId: '1:835318680713:ios:b341c4bebe4f21c7a08a58',
    messagingSenderId: '835318680713',
    projectId: 'studio-4536174912-ee6ca',
    storageBucket: 'studio-4536174912-ee6ca.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRGsAIHLwZrMpN0803e5n3zxQAvIt20MQ',
    appId: '1:835318680713:ios:b341c4bebe4f21c7a08a58',
    messagingSenderId: '835318680713',
    projectId: 'studio-4536174912-ee6ca',
    storageBucket: 'studio-4536174912-ee6ca.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdx1Qxmt89XJmQTLYuUw96E32_Yu07iPs',
    appId: '1:835318680713:web:88e324f919400293a08a58',
    messagingSenderId: '835318680713',
    projectId: 'studio-4536174912-ee6ca',
    authDomain: 'studio-4536174912-ee6ca.firebaseapp.com',
    storageBucket: 'studio-4536174912-ee6ca.firebasestorage.app',
  );
}
